import sourceArticles from "@/data/knowledge-articles.json";

export type KnowledgeCategory = "Financial Analysis" | "Corporate Finance" | "Economics" | "Valuation" | "Investor Judgment";
export type KnowledgeBlock =
  | { type: "paragraph"; text: string }
  | { type: "heading"; text: string; level: 3 | 4 }
  | { type: "table"; rows: string[][]; caption?: string }
  | { type: "diagram"; title: string; caption: string; nodes: string[]; kind: "flow" | "grid" };
export type KnowledgeSection = { id: string; title: string; blocks: KnowledgeBlock[] };
export type KnowledgeArticle = { slug: string; title: string; category: KnowledgeCategory; purpose: string; status: "Complete"; source: string; relatedSlugs: string[]; frameworkLinks?: { title: string; slug: string }[]; sections: KnowledgeSection[]; readingTime?: string };

const diagrams: Partial<Record<string, Extract<KnowledgeBlock, { type: "diagram" }>>> = {
  "financial-statements": { type: "diagram", title: "The three financial statements", caption: "The source treats the income statement, balance sheet, and cash flow statement as connected views of one business.", kind: "grid", nodes: ["Income statement", "Balance sheet", "Cash flow statement"] },
  "financial-ratios": { type: "diagram", title: "Ratio families", caption: "The handbook organizes ratios by the questions they answer; a single ratio does not describe the whole business.", kind: "grid", nodes: ["Profitability", "Margins", "Liquidity", "Leverage", "Efficiency", "Valuation"] },
  "owner-earnings": { type: "diagram", title: "Two views of available cash", caption: "The source distinguishes total capital expenditure in free cash flow from the maintenance spending used to estimate owner earnings.", kind: "grid", nodes: ["Operating cash flow", "Total capital expenditure → FCF", "Maintenance capital expenditure → owner earnings"] },
  "cost-of-capital": { type: "diagram", title: "The cost-of-capital architecture", caption: "Debt and equity both have a cost. Their combined required return informs the hurdle for investment decisions.", kind: "grid", nodes: ["Cost of debt", "Cost of equity", "WACC", "Investment hurdle"] },
  "capital-allocation": { type: "diagram", title: "The uses of cash", caption: "The handbook presents five choices for cash generated by the business; the diagram does not rank or score them.", kind: "grid", nodes: ["Reinvestment", "Dividends", "Share buybacks", "Acquisitions", "Debt reduction"] },
  "economic-indicators": { type: "diagram", title: "Economic dashboard", caption: "The source cautions against relying on any one gauge to interpret the economy.", kind: "grid", nodes: ["GDP", "Inflation", "Interest rates", "Employment", "PMI", "Consumer confidence", "Yield curve"] },
  "discounted-cash-flow": { type: "diagram", title: "The DCF sequence", caption: "Cash-flow projections and terminal value are brought to present value before they are combined.", kind: "flow", nodes: ["Forecast cash flow", "Discount each period", "Estimate terminal value", "Discount terminal value", "Combine present values"] },
  "margin-of-safety": { type: "diagram", title: "The margin-of-safety relationship", caption: "The source defines the margin as the difference between an estimated intrinsic value and a lower market price, expressed relative to estimated value.", kind: "grid", nodes: ["Estimated intrinsic value", "Market price", "Gap as a share of estimated value"] },
  "circle-of-competence": { type: "diagram", title: "Learning within a circle of competence", caption: "The source distinguishes recognition, understanding, and judgment while emphasizing awareness of the boundary of one's knowledge.", kind: "flow", nodes: ["Recognition", "Understanding", "Judgment"] },
};

const articles = (sourceArticles as unknown as KnowledgeArticle[]).map((article) => {
  const diagram = diagrams[article.slug];
  return {
    ...article,
    sections: diagram ? article.sections.map((section, index) => index === 0 ? { ...section, blocks: [...section.blocks, diagram] } : section) : article.sections,
  };
});

export const knowledgeArticles = articles.map((article) => {
  const words = [article.title, article.purpose, ...article.sections.flatMap((section) => [section.title, ...section.blocks.flatMap((block) => block.type === "paragraph" || block.type === "heading" ? [block.text] : block.type === "table" ? block.rows.flat() : [block.title, block.caption, ...block.nodes])])].join(" ").trim().split(/\s+/).filter(Boolean).length;
  return { ...article, readingTime: `${Math.max(1, Math.ceil(words / 220))} min read` };
});

export function getKnowledgeArticle(slug: string) { return knowledgeArticles.find((article) => article.slug === slug); }
